from __future__ import annotations

import argparse
import logging
from pathlib import Path

from untappd_pairing import describe, store
from utils.logging import configure_logging

logger = logging.getLogger(__name__)


def find_suspect_descriptions(pairings: dict[str, dict[str, object]]) -> list[tuple[str, str]]:
    suspects = []
    for key, entry in sorted(pairings.items()):
        description = entry.get("description")
        if not isinstance(description, str):
            continue
        reason = describe.rejection_reason(description)
        if reason is not None:
            suspects.append((key, reason))
    return suspects


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Report AI beer descriptions that fail the plausibility check.")
    parser.add_argument("--drop", action="store_true", help="remove the offending descriptions from the store")
    parser.add_argument("--path", type=Path, default=store.PAIRINGS_PATH, help="path to pairings.json")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    pairings_store = store.PairingsStore.load(args.path)
    described = sum(1 for entry in pairings_store.pairings.values() if entry.get("description"))
    suspects = find_suspect_descriptions(pairings_store.pairings)

    if not suspects:
        logger.info("All %d descriptions look fine", described)
        return 0

    for key, reason in suspects:
        logger.warning("%s (%s): %s", key, reason, pairings_store.pairings[key]["description"])

    if not args.drop:
        logger.warning("%d of %d descriptions are suspect; rerun with --drop to remove them", len(suspects), described)
        return 1

    for key, _reason in suspects:
        del pairings_store.pairings[key]["description"]
    pairings_store.save(args.path)
    # Descriptions are only written when a pairing is recorded, so a dropped one comes back the
    # next time the beer shows up on tap -- by then generated by the current prompt.
    logger.info("Dropped %d descriptions from %s", len(suspects), args.path)
    return 0


if __name__ == "__main__":
    configure_logging()
    raise SystemExit(main())
